### ISSUE TITLE
The node cannot synchronize data normally, panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Alteryy** [CortexFoundation/Cortex_Release#14]
start command： ./cortex --port 37566 --rpc --rpccorsdomain '*' --rpcport 12782 --rpcaddr 0.0.0.0 --rpcapi web3,personal,ctxc,miner,net,txpool --verbosity 4 --gcmode archive > ctxc.log 

uname: #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

INFO [12-24|22:24:12.530] Initialised chain configuration          config="{ChainID: 21 Homestead: 0 DAO: 0 DAOSupport: false TangerineWhistle(EIP150): 0 SpuriousDragon(EIP155): 0 SpuriousDragon(EIP158): 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: <nil> Engine: cuckoo}"
WARN [12-24|22:24:12.530] Memory status                            total=15771 allowance=5257 cuda=false device= threads=0 algo=cuckaroo mine=false
INFO [12-24|22:24:12.531] Initialising Cortex protocol             versions="[65 64 63]" network=21 dbversion=8
ERROR[12-24|22:24:12.531] library open failed                      path=plugins/libcvm_runtime.so error="/opt/ctxc/cortex-Linux-x86_64-v1.10.0-a0f6ed12/plugins/libcvm_runtime.so: cannot open shared object file: No such file or directory"
ERROR[12-24|22:24:12.531] infer helper                             init cvm plugin error=
INFO [12-24|22:24:12.532] Loaded most recent local header          number=3040418 hash="dd135a…83cae1" td=8241896392 age=10m33s
INFO [12-24|22:24:12.532] Loaded most recent local full block      number=3040418 hash="dd135a…83cae1" td=8241896392 age=10m33s
INFO [12-24|22:24:12.532] Loaded most recent local fast block      number=3040418 hash="dd135a…83cae1" td=8241896392 age=10m33s
INFO [12-24|22:24:12.533] Loaded local transaction journal         transactions=0 dropped=0
INFO [12-24|22:24:12.533] Regenerated local transaction journal    transactions=0 accounts=0
INFO [12-24|22:24:12.533] Check point                              section=69 number=2293759 hash="bf7464…6749f5" genesis="21d6ce…7762c1" ok=true
INFO [12-24|22:24:12.540] Deep froze chain segment                 blocks=4   elapsed=10.692ms    number=2950418 hash="2a04f7…1ed41f"
INFO [12-24|22:24:12.572] Started nas v.1.0                        config="&{protocol:{Name:nas Version:2 Length:128 Run:0x144c7a0 NodeInfo:0x14476e0 PeerInfo:0x1447e20 DialCandidates:<nil> Attributes:[]} config:0xc00024e5e8 monitor:0xc0000ee2c0 peerMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} peers:map[] nasCache:0xc014ed2480 queryCache:0xc014ed2510 nasCounter:0}" mode=normal
INFO [12-24|22:24:12.573] IPC endpoint opened                      url=/root/.cortex/cortex.ipc
INFO [12-24|22:24:12.573] HTTP endpoint opened                     url=http://[::]:12782/       cors=* vhosts=localhost
INFO [12-24|22:24:12.577] Started P2P networking                   self=enode://197ec486b088eec4c8db414ea74eac4a0e3e6eb4a6f9a25bd8ae6dca50a28fb5a37b79fda4d45299058a406c084bf30b8aec9e5fb41fb72c7d1c176a7b41c441@127.0.0.1:37566
INFO [12-24|22:24:12.626] Imported new nas segment                 ih=d31d1b0f588069aa6f36de5a7025a8d73a9a49f6 size=60.81MiB  files=2  pieces=973 seg=1 cited=0 peers=25 status=7 elapsed="83.658µs"
INFO [12-24|22:24:12.635] Imported new nas segment                 ih=de58609743e5cd0cb18798d91a196f418ac25016 size=147.12KiB files=1  pieces=10  seg=1 cited=0 peers=25 status=7 elapsed="913.147µs"
INFO [12-24|22:24:12.635] Imported new nas segment                 ih=3145ad19228c1cd2d051314e72f26c1ce77b7f02 size=398.21KiB files=2  pieces=25  seg=1 cited=0 peers=25 status=7 elapsed="925.521µs"
INFO [12-24|22:24:12.692] Imported new nas segment                 ih=9dbde0099a270c23d5dec0acb0ac537b0fb35c27 size=4.15MiB   files=2  pieces=266 seg=1 cited=0 peers=25 status=7 elapsed="286.952µs"
INFO [12-24|22:24:12.695] Imported new nas segment                 ih=ad3d77101866c0c7520aa41a5c41eee92500f809 size=147.12KiB files=1  pieces=10  seg=1 cited=0 peers=25 status=7 elapsed="443.013µs"
INFO [12-24|22:24:12.697] Imported new nas segment                 ih=67b315aac2fbdbaf97ac8d40df0b9c435b65c4aa size=3.12KiB   files=1  pieces=1   seg=1 cited=0 peers=25 status=7 elapsed="57.731µs"
INFO [12-24|22:24:12.698] Imported new nas segment                 ih=b3d2f3d4f395924ca4cf5bd1843d49de043c959c size=3.12KiB   files=1  pieces=1   seg=1 cited=0 peers=25 status=7 elapsed="55.642µs"
INFO [12-24|22:24:12.702] Imported new nas segment                 ih=b08e2c6103157ab99040cdc9ddfee05e93763f6c size=147.12KiB files=1  pieces=10  seg=1 cited=0 peers=25 status=7 elapsed="58.09µs"
INFO [12-24|22:24:12.746] Imported new nas segment                 ih=c599d0fa8d816cf83c5018232453c6ae57db4ab3 size=24.75MiB  files=2  pieces=792 seg=1 cited=0 peers=25 status=7 elapsed="614.383µs"
INFO [12-24|22:24:12.746] Imported new nas segment                 ih=ae5a301ddfe1d4be9848adf8dde9f78d7ebba919 size=3.12KiB   files=1  pieces=1   seg=1 cited=0 peers=25 status=7 elapsed="57.443µs"
INFO [12-24|22:24:12.753] Imported new nas segment                 ih=b2f5b0036877be22c6101bdfa5f2c7927fc35ef8 size=33.46KiB  files=2  pieces=3   seg=1 cited=0 peers=25 status=7 elapsed=1.439ms
INFO [12-24|22:24:12.753] Imported new nas segment                 ih=04615009127a4829d32d22dddb45664a2aee8067 size=147.12KiB files=1  pieces=10  seg=1 cited=0 peers=25 status=7 elapsed=1.450ms
INFO [12-24|22:24:12.753] Imported new nas segment                 ih=6b3fd83c1fb05ae5145673218b53a1411460f3e0 size=3.12KiB   files=1  pieces=1   seg=1 cited=0 peers=25 status=7 elapsed=1.429ms
INFO [12-24|22:24:12.753] Imported new nas segment                 ih=5a49fed84aaf368cbf472cc06e42f93a93d92db5 size=1.57MiB   files=2  pieces=101 seg=1 cited=0 peers=25 status=7 elapsed=1.527ms
INFO [12-24|22:24:13.593] Block synchronisation started 
INFO [12-24|22:24:14.577] Internal ipc connection established      ipc=/root/.cortex/cortex.ipc rpc=http://127.0.0.1:8545 local=true
INFO [12-24|22:24:14.577] Loading storage data ... ...             latest=3040412 checkpoint=2755628 root="c5f482…862fb1" version=1 current=3040418
INFO [12-24|22:24:14.578] Fs storage version check passed          name=mainnet number=395964  version="e78706…7e5dcc" blocks=110 files=53 txs=327
WARN [12-24|22:24:15.582] Finish sync, listener will be stopped    current=3040418 elapsed=10m57.933s
INFO [12-24|22:24:17.805] Downloader queue stats                   receiptTasks=0 blockTasks=0 itemSize=716.50B throttle=8192
INFO [12-24|22:24:17.821] Imported new chain segment               blocks=24  txs=1   mgas=0.021 elapsed=15.046ms    mgasps=1.396 number=3040442 hash="71b8f2…0bb884" hps=115.111H age=4m50s  dirty=63.44KiB
INFO [12-24|22:24:17.935] Imported new chain segment               blocks=28  txs=5   mgas=0.105 elapsed=22.264ms    mgasps=4.716 number=3040470 hash="e488c0…27143d" hps=115.778H age=33s    dirty=145.52KiB
INFO [12-24|22:24:21.005] Imported new chain segment               blocks=1   txs=0   mgas=0.000 elapsed="542.169µs" mgasps=0.000 number=3040471 hash="b45842…cee062" hps=115.778H age=25s    dirty=148.03KiB
INFO [12-24|22:24:21.052] Imported new chain segment               blocks=2   txs=3   mgas=0.063 elapsed=1.778ms     mgasps=35.416 number=3040473 hash="3c4fb6…6863dc" hps=115.852H age=9s     dirty=161.84KiB
INFO [12-24|22:24:29.718] Imported new chain segment               blocks=1   txs=1   mgas=0.021 elapsed="922.182µs" mgasps=22.772 number=3040474 hash="ff7a6f…a71124" hps=115.926H age=11s    dirty=167.99KiB
INFO [12-24|22:24:31.483] Imported new chain segment               blocks=1   txs=0   mgas=0.000 elapsed="535.355µs" mgasps=0.000  number=3040475 hash="aa0e9c…98032e" hps=115.926H age=2s     dirty=170.44KiB
INFO [12-24|22:24:34.241] Imported new chain segment               blocks=1   txs=0   mgas=0.000 elapsed="548.172µs" mgasps=0.000  number=3040476 hash="0417b2…4ef06d" hps=116.000H age=3s     dirty=172.94KiB
INFO [12-24|22:24:42.859] Imported new chain segment               blocks=1   txs=1   mgas=0.021 elapsed="645.269µs" mgasps=32.545 number=3040477 hash="04e8c2…44d0a9" hps=116.074H age=8s     dirty=178.97KiB
WARN [12-24|22:24:46.908] Synapse Engine has not been initalized, should new it first 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1469726]

goroutine 360 [running]:
github.com/CortexFoundation/CortexTheseus/vendor/github.com/CortexFoundation/inference/synapse.(*Synapse).GetGasByInfoHashWithSize(0x0, 0xc02489a2a0, 0x2a, 0x400f7, 0x15, 0x0, 0x0, 0x2)
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/github.com/CortexFoundation/inference/synapse/synapse.go:152 +0x26
github.com/CortexFoundation/CortexTheseus/core/vm.(*CVM).OpsInfer(0xc01b52b500, 0x3e4c3266e1688cfe, 0xebd4b0d1740a16cb, 0x1a63c36e, 0x0, 0xc01ff28500, 0x0)
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/core/vm/cvm.go:678 +0x145
github.com/CortexFoundation/CortexTheseus/core/vm.gasInferArray(0x2bc, 0x2bc, 0x190, 0x190, 0xc8, 0x2bc, 0x1388, 0x32, 0x61a8, 0xc01b52b500, ...)
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/core/vm/gas_table.go:670 +0x116
github.com/CortexFoundation/CortexTheseus/core/vm.(*CVMInterpreter).Run(0xc021797500, 0xc018e745b0, 0xc01db06938, 0x4, 0x4, 0xc018e73700, 0x0, 0x0, 0x0, 0x0, ...)
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/core/vm/interpreter.go:437 +0x22ab
github.com/CortexFoundation/CortexTheseus/core/vm.run(0xc01b52b500, 0xc018e745b0, 0xc01db06938, 0x4, 0x4, 0xbf6f3fd389d44b00, 0x0, 0x0, 0x0, 0x0, ...)
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/core/vm/cvm.go:96 +0x29f
github.com/CortexFoundation/CortexTheseus/core/vm.(*CVM).Call(0xc01b52b500, 0x1ecdb80, 0xc018e73800, 0x164bb107f60dfba1, 0xde7fc9b3ee2ecb6, 0xd7fa996, 0xc01db06938, 0x4, 0x4, 0x2d73a8, ...)
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/core/vm/cvm.go:289 +0x6b7
github.com/CortexFoundation/CortexTheseus/core.(*StateTransition).TransitionDb(0xc021372000, 0x1effbc0, 0xc021d55260, 0xc0237d04f0, 0xc0237d04f8, 0xc021372000, 0xc021d55260, 0xc021d55260, 0x1c15d80)
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/core/state_transition.go:329 +0x459
github.com/CortexFoundation/CortexTheseus/core.ApplyMessage(0xc01b52b500, 0x1effbc0, 0xc021d55260, 0xc0237d04f0, 0xc0237d04f8, 0xc018e71a40, 0xc00027be60, 0xc00027be90, 0xc00027bec0, 0xc00027bef0, ...)
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/core/state_transition.go:152 +0x65
github.com/CortexFoundation/CortexTheseus/core.applyTransaction(0xc018fade00, 0xcc6d56fd6e8a6d8b, 0x88958d2059cffdc2, 0x89e893e6, 0x5, 0xc018fafb60, 0x2dc6c0, 0xc018e71980, 0xc01db06938, 0x4, ...)
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/core/state_processor.go:110 +0x177
github.com/CortexFoundation/CortexTheseus/core.ApplyTransaction(0x2c112e0, 0x1edcee0, 0xc017a46000, 0xc015cbd998, 0xc0237d04f0, 0xc0237d04f8, 0xc02051b760, 0xc020539500, 0xc018fb4210, 0xc0205396d0, ...)
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/core/state_processor.go:165 +0x29d
github.com/CortexFoundation/CortexTheseus/miner.(*worker).commitTransaction(0xc00029afc0, 0xc018fb4210, 0x0, 0x0, 0x693eebfc00000000, 0xdf0e4a3589e893e6, 0x0, 0x0, 0xcb32a5, 0xcb4485)
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/miner/worker.go:728 +0x185
github.com/CortexFoundation/CortexTheseus/miner.(*worker).commitTransactions(0xc00029afc0, 0xc01e365830, 0x0, 0x0, 0x0, 0x0, 0x1)
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/miner/worker.go:806 +0x485
github.com/CortexFoundation/CortexTheseus/miner.(*worker).mainLoop(0xc00029afc0)
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/miner/worker.go:500 +0x72a
created by github.com/CortexFoundation/CortexTheseus/miner.newWorker
        /root/CortexTheseus/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/miner/worker.go:230 +0x56e

**Comment by ucwong** [comment]
![image](https://user-images.githubusercontent.com/22344498/103116865-e248cc00-46a2-11eb-8bbd-bf94571cefdd.png)
