### ISSUE TITLE
为什么项目源码在这里没有？

### ISSUE THREAD

**Issue by harrylee2015** [CortexFoundation/Cortex_Release#3]
# 只有编译好的二进制挖矿测试文件？ 项目代码计划什么时候开源啊

**Comment by SiNZeRo** [comment]
> # 只有编译好的二进制挖矿测试文件？ 项目代码计划什么时候开源啊
@harrylee2015 

> Bernard and Dolores TestNet serve as a big milestone as this is the first to enable AI inference on the blockchain to showcase to the world. Considering that the development of the Cortex main chain has yet to be complete, in order to avoid binary copycats, Cortex selectively opens a portion of the source code to prevent plagiarism from other projects, while everyone can read the TestNet’s blockchain data to verify its legitimacy. Once the main chain is released, Cortex will go fully open-source on the blockchain.

[](https://medium.com/cortexlabs/the-first-ai-on-blockchain-testnet-release-in-the-history-of-mankind-bernard-dolores-beta-b617198273c1)
